services:
  backend:
    build:
      context: .
      dockerfile: ./infra/docker/prod/Dockerfile
      target: server-runtime
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: ./infra/docker/dev/Dockerfile
      target: client-runtime
    container_name: frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
