services:
  backend:
    build:
      context: .
      target: server-runtime
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/repo/backend
      - bun-cache:/root/.bun

  frontend:
    build:
      context: .
      target: client-runtime
    container_name: frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
volumes:
  bun-cache:
