services:
  server:
    build:
      context: .
      dockerfile: infra/docker/prod/server.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - packages/server/.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: .
      dockerfile: infra/docker/prod/client.Dockerfile
    ports:
      - '5173:80'
    env_file:
      - packages/client/.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5173/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
